package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type policyTx interface{}

type policyQueries interface {
	WithTx(tx policyTx) policyQueries

	assignPublicKeyToAttributeDefinition(ctx context.Context, arg assignPublicKeyToAttributeDefinitionParams) (AttributeDefinitionPublicKeyMap, error)
	assignPublicKeyToAttributeValue(ctx context.Context, arg assignPublicKeyToAttributeValueParams) (AttributeValuePublicKeyMap, error)
	assignPublicKeyToNamespace(ctx context.Context, arg assignPublicKeyToNamespaceParams) (AttributeNamespacePublicKeyMap, error)
	createAttribute(ctx context.Context, arg createAttributeParams) (string, error)
	createAttributeValue(ctx context.Context, arg createAttributeValueParams) (string, error)
	createCustomAction(ctx context.Context, arg createCustomActionParams) (string, error)
	createKey(ctx context.Context, arg createKeyParams) (string, error)
	createKeyAccessServer(ctx context.Context, arg createKeyAccessServerParams) (string, error)
	createNamespace(ctx context.Context, arg createNamespaceParams) (string, error)
	createObligation(ctx context.Context, arg createObligationParams) (createObligationRow, error)
	createObligationTrigger(ctx context.Context, arg createObligationTriggerParams) (createObligationTriggerRow, error)
	createObligationValue(ctx context.Context, arg createObligationValueParams) (createObligationValueRow, error)
	createOrListActionsByName(ctx context.Context, actionNames []string) ([]createOrListActionsByNameRow, error)
	createProviderConfig(ctx context.Context, arg createProviderConfigParams) (createProviderConfigRow, error)
	createRegisteredResource(ctx context.Context, arg createRegisteredResourceParams) (string, error)
	createRegisteredResourceActionAttributeValues(ctx context.Context, arg []createRegisteredResourceActionAttributeValuesParams) (int64, error)
	createRegisteredResourceValue(ctx context.Context, arg createRegisteredResourceValueParams) (string, error)
	createResourceMapping(ctx context.Context, arg createResourceMappingParams) (string, error)
	createResourceMappingGroup(ctx context.Context, arg createResourceMappingGroupParams) (string, error)
	createSubjectConditionSet(ctx context.Context, arg createSubjectConditionSetParams) (string, error)
	createSubjectMapping(ctx context.Context, arg createSubjectMappingParams) (string, error)
	deleteAllObligationTriggersForValue(ctx context.Context, obligationValueID string) (int64, error)
	deleteAllUnmappedSubjectConditionSets(ctx context.Context) ([]string, error)
	deleteAttribute(ctx context.Context, id string) (int64, error)
	deleteAttributeValue(ctx context.Context, id string) (int64, error)
	deleteCustomAction(ctx context.Context, id string) (int64, error)
	deleteKey(ctx context.Context, id string) (int64, error)
	deleteKeyAccessServer(ctx context.Context, id string) (int64, error)
	deleteNamespace(ctx context.Context, id string) (int64, error)
	deleteObligation(ctx context.Context, arg deleteObligationParams) (string, error)
	deleteObligationTrigger(ctx context.Context, id string) (string, error)
	deleteObligationValue(ctx context.Context, arg deleteObligationValueParams) (string, error)
	deleteProviderConfig(ctx context.Context, id string) (int64, error)
	deleteRegisteredResource(ctx context.Context, id string) (int64, error)
	deleteRegisteredResourceActionAttributeValues(ctx context.Context, registeredResourceValueID string) (int64, error)
	deleteRegisteredResourceValue(ctx context.Context, id string) (int64, error)
	deleteResourceMapping(ctx context.Context, id string) (int64, error)
	deleteResourceMappingGroup(ctx context.Context, id string) (int64, error)
	deleteSubjectConditionSet(ctx context.Context, id string) (int64, error)
	deleteSubjectMapping(ctx context.Context, id string) (int64, error)
	getAction(ctx context.Context, arg getActionParams) (getActionRow, error)
	getAttribute(ctx context.Context, arg getAttributeParams) (getAttributeRow, error)
	getAttributeValue(ctx context.Context, arg getAttributeValueParams) (getAttributeValueRow, error)
	getBaseKey(ctx context.Context) ([]byte, error)
	getKey(ctx context.Context, arg getKeyParams) (getKeyRow, error)
	getKeyAccessServer(ctx context.Context, arg getKeyAccessServerParams) (getKeyAccessServerRow, error)
	getNamespace(ctx context.Context, arg getNamespaceParams) (getNamespaceRow, error)
	getObligation(ctx context.Context, arg getObligationParams) (getObligationRow, error)
	getObligationValue(ctx context.Context, arg getObligationValueParams) (getObligationValueRow, error)
	getObligationValuesByFQNs(ctx context.Context, arg getObligationValuesByFQNsParams) ([]getObligationValuesByFQNsRow, error)
	getObligationsByFQNs(ctx context.Context, arg getObligationsByFQNsParams) ([]getObligationsByFQNsRow, error)
	getProviderConfig(ctx context.Context, arg getProviderConfigParams) (getProviderConfigRow, error)
	getRegisteredResource(ctx context.Context, arg getRegisteredResourceParams) (getRegisteredResourceRow, error)
	getRegisteredResourceValue(ctx context.Context, arg getRegisteredResourceValueParams) (getRegisteredResourceValueRow, error)
	getResourceMapping(ctx context.Context, id string) (getResourceMappingRow, error)
	getResourceMappingGroup(ctx context.Context, id string) (getResourceMappingGroupRow, error)
	getSubjectConditionSet(ctx context.Context, id string) (getSubjectConditionSetRow, error)
	getSubjectMapping(ctx context.Context, id string) (getSubjectMappingRow, error)
	keyAccessServerExists(ctx context.Context, arg keyAccessServerExistsParams) (bool, error)
	listActions(ctx context.Context, arg listActionsParams) ([]listActionsRow, error)
	listAttributeValues(ctx context.Context, arg listAttributeValuesParams) ([]listAttributeValuesRow, error)
	listAttributesByDefOrValueFqns(ctx context.Context, arg listAttributesByDefOrValueFqnsParams) ([]listAttributesByDefOrValueFqnsRow, error)
	listAttributesDetail(ctx context.Context, arg listAttributesDetailParams) ([]listAttributesDetailRow, error)
	listAttributesSummary(ctx context.Context, arg listAttributesSummaryParams) ([]listAttributesSummaryRow, error)
	listKeyAccessServerGrants(ctx context.Context, arg listKeyAccessServerGrantsParams) ([]listKeyAccessServerGrantsRow, error)
	listKeyAccessServers(ctx context.Context, arg listKeyAccessServersParams) ([]listKeyAccessServersRow, error)
	listKeyMappings(ctx context.Context, arg listKeyMappingsParams) ([]listKeyMappingsRow, error)
	listKeys(ctx context.Context, arg listKeysParams) ([]listKeysRow, error)
	listNamespaces(ctx context.Context, arg listNamespacesParams) ([]listNamespacesRow, error)
	listObligationTriggers(ctx context.Context, arg listObligationTriggersParams) ([]listObligationTriggersRow, error)
	listObligations(ctx context.Context, arg listObligationsParams) ([]listObligationsRow, error)
	listProviderConfigs(ctx context.Context, arg listProviderConfigsParams) ([]listProviderConfigsRow, error)
	listRegisteredResourceValues(ctx context.Context, arg listRegisteredResourceValuesParams) ([]listRegisteredResourceValuesRow, error)
	listRegisteredResources(ctx context.Context, arg listRegisteredResourcesParams) ([]listRegisteredResourcesRow, error)
	listResourceMappingGroups(ctx context.Context, arg listResourceMappingGroupsParams) ([]listResourceMappingGroupsRow, error)
	listResourceMappings(ctx context.Context, arg listResourceMappingsParams) ([]listResourceMappingsRow, error)
	listResourceMappingsByFullyQualifiedGroup(ctx context.Context, arg listResourceMappingsByFullyQualifiedGroupParams) ([]listResourceMappingsByFullyQualifiedGroupRow, error)
	listSubjectConditionSets(ctx context.Context, arg listSubjectConditionSetsParams) ([]listSubjectConditionSetsRow, error)
	listSubjectMappings(ctx context.Context, arg listSubjectMappingsParams) ([]listSubjectMappingsRow, error)
	matchSubjectMappings(ctx context.Context, selectors []string) ([]matchSubjectMappingsRow, error)
	removeKeyAccessServerFromAttribute(ctx context.Context, arg removeKeyAccessServerFromAttributeParams) (int64, error)
	removeKeyAccessServerFromAttributeValue(ctx context.Context, arg removeKeyAccessServerFromAttributeValueParams) (int64, error)
	removeKeyAccessServerFromNamespace(ctx context.Context, arg removeKeyAccessServerFromNamespaceParams) (int64, error)
	removePublicKeyFromAttributeDefinition(ctx context.Context, arg removePublicKeyFromAttributeDefinitionParams) (int64, error)
	removePublicKeyFromAttributeValue(ctx context.Context, arg removePublicKeyFromAttributeValueParams) (int64, error)
	removePublicKeyFromNamespace(ctx context.Context, arg removePublicKeyFromNamespaceParams) (int64, error)
	rotatePublicKeyForAttributeDefinition(ctx context.Context, arg rotatePublicKeyForAttributeDefinitionParams) ([]string, error)
	rotatePublicKeyForAttributeValue(ctx context.Context, arg rotatePublicKeyForAttributeValueParams) ([]string, error)
	rotatePublicKeyForNamespace(ctx context.Context, arg rotatePublicKeyForNamespaceParams) ([]string, error)
	setBaseKey(ctx context.Context, keyAccessServerKeyID pgtype.UUID) (int64, error)
	updateAttribute(ctx context.Context, arg updateAttributeParams) (int64, error)
	updateAttributeValue(ctx context.Context, arg updateAttributeValueParams) (int64, error)
	updateCustomAction(ctx context.Context, arg updateCustomActionParams) (int64, error)
	updateKey(ctx context.Context, arg updateKeyParams) (int64, error)
	updateKeyAccessServer(ctx context.Context, arg updateKeyAccessServerParams) (int64, error)
	updateNamespace(ctx context.Context, arg updateNamespaceParams) (int64, error)
	updateObligation(ctx context.Context, arg updateObligationParams) (int64, error)
	updateObligationValue(ctx context.Context, arg updateObligationValueParams) (int64, error)
	updateProviderConfig(ctx context.Context, arg updateProviderConfigParams) (int64, error)
	updateRegisteredResource(ctx context.Context, arg updateRegisteredResourceParams) (int64, error)
	updateRegisteredResourceValue(ctx context.Context, arg updateRegisteredResourceValueParams) (int64, error)
	updateResourceMapping(ctx context.Context, arg updateResourceMappingParams) (int64, error)
	updateResourceMappingGroup(ctx context.Context, arg updateResourceMappingGroupParams) (int64, error)
	updateSubjectConditionSet(ctx context.Context, arg updateSubjectConditionSetParams) (int64, error)
	updateSubjectMapping(ctx context.Context, arg updateSubjectMappingParams) (int64, error)
	upsertAttributeDefinitionFqn(ctx context.Context, attributeID string) ([]upsertAttributeDefinitionFqnRow, error)
	upsertAttributeNamespaceFqn(ctx context.Context, namespaceID string) ([]upsertAttributeNamespaceFqnRow, error)
	upsertAttributeValueFqn(ctx context.Context, valueID string) ([]upsertAttributeValueFqnRow, error)
}
