// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attribute_fqn.sql

package dbsqlite

import (
	"context"
)

const upsertAttributeDefinitionFqn = `-- name: UpsertAttributeDefinitionFqn :many
WITH new_fqns_cte AS (
    -- get attribute definition fqns
    SELECT
        ns.id AS namespace_id,
        ad.id AS attribute_id,
        NULL AS value_id,
        CONCAT('https://', ns.name, '/attr/', ad.name) AS fqn
    FROM attribute_definitions ad
    JOIN attribute_namespaces ns ON ad.namespace_id = ns.id
    WHERE ad.id = $1 
    UNION
    -- get attribute value fqns
    SELECT
        ns.id as namespace_id,
        ad.id as attribute_id,
        av.id as value_id,
        CONCAT('https://', ns.name, '/attr/', ad.name, '/value/', av.value) AS fqn
    FROM attribute_values av
    JOIN attribute_definitions ad on av.attribute_definition_id = ad.id
    JOIN attribute_namespaces ns on ad.namespace_id = ns.id
    WHERE ad.id = $1 
)
INSERT OR REPLACE INTO attribute_fqns (id, namespace_id, attribute_id, value_id, fqn)
SELECT
    COALESCE(
        (
            SELECT af.id
            FROM attribute_fqns af
            WHERE af.namespace_id IS nf.namespace_id
              AND af.attribute_id IS nf.attribute_id
              AND af.value_id IS nf.value_id
        ),
        gen_random_uuid()
    ),
    nf.namespace_id,
    nf.attribute_id,
    nf.value_id,
    nf.fqn
FROM new_fqns_cte nf
RETURNING
    COALESCE(namespace_id, '') AS namespace_id,
    COALESCE(attribute_id, '') AS attribute_id,
    COALESCE(value_id, '') AS value_id,
    fqn
`

type UpsertAttributeDefinitionFqnRow struct {
	NamespaceID string `json:"namespace_id"`
	AttributeID string `json:"attribute_id"`
	ValueID     string `json:"value_id"`
	Fqn         string `json:"fqn"`
}

// UpsertAttributeDefinitionFqn
//
//	WITH new_fqns_cte AS (
//	    -- get attribute definition fqns
//	    SELECT
//	        ns.id AS namespace_id,
//	        ad.id AS attribute_id,
//	        NULL AS value_id,
//	        CONCAT('https://', ns.name, '/attr/', ad.name) AS fqn
//	    FROM attribute_definitions ad
//	    JOIN attribute_namespaces ns ON ad.namespace_id = ns.id
//	    WHERE ad.id = $1
//	    UNION
//	    -- get attribute value fqns
//	    SELECT
//	        ns.id as namespace_id,
//	        ad.id as attribute_id,
//	        av.id as value_id,
//	        CONCAT('https://', ns.name, '/attr/', ad.name, '/value/', av.value) AS fqn
//	    FROM attribute_values av
//	    JOIN attribute_definitions ad on av.attribute_definition_id = ad.id
//	    JOIN attribute_namespaces ns on ad.namespace_id = ns.id
//	    WHERE ad.id = $1
//	)
//	INSERT OR REPLACE INTO attribute_fqns (id, namespace_id, attribute_id, value_id, fqn)
//	SELECT
//	    COALESCE(
//	        (
//	            SELECT af.id
//	            FROM attribute_fqns af
//	            WHERE af.namespace_id IS nf.namespace_id
//	              AND af.attribute_id IS nf.attribute_id
//	              AND af.value_id IS nf.value_id
//	        ),
//	        gen_random_uuid()
//	    ),
//	    nf.namespace_id,
//	    nf.attribute_id,
//	    nf.value_id,
//	    nf.fqn
//	FROM new_fqns_cte nf
//	RETURNING
//	    COALESCE(namespace_id, '') AS namespace_id,
//	    COALESCE(attribute_id, '') AS attribute_id,
//	    COALESCE(value_id, '') AS value_id,
//	    fqn
func (q *Queries) UpsertAttributeDefinitionFqn(ctx context.Context, attributeID string) ([]UpsertAttributeDefinitionFqnRow, error) {
	rows, err := q.db.QueryContext(ctx, upsertAttributeDefinitionFqn, attributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertAttributeDefinitionFqnRow
	for rows.Next() {
		var i UpsertAttributeDefinitionFqnRow
		if err := rows.Scan(
			&i.NamespaceID,
			&i.AttributeID,
			&i.ValueID,
			&i.Fqn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttributeNamespaceFqn = `-- name: UpsertAttributeNamespaceFqn :many
WITH new_fqns_cte AS (
    -- get namespace fqns
    SELECT
        ns.id as namespace_id,
        NULL as attribute_id,
        NULL as value_id,
        CONCAT('https://', ns.name) AS fqn
    FROM attribute_namespaces ns
    WHERE ns.id = $1 
    UNION
    -- get attribute definition fqns
    SELECT
        ns.id as namespace_id,
        ad.id as attribute_id,
        NULL as value_id,
        CONCAT('https://', ns.name, '/attr/', ad.name) AS fqn
    FROM attribute_definitions ad
    JOIN attribute_namespaces ns on ad.namespace_id = ns.id
    WHERE ns.id = $1 
    UNION
    -- get attribute value fqns
    SELECT
        ns.id as namespace_id,
        ad.id as attribute_id,
        av.id as value_id,
        CONCAT('https://', ns.name, '/attr/', ad.name, '/value/', av.value) AS fqn
    FROM attribute_values av
    JOIN attribute_definitions ad on av.attribute_definition_id = ad.id
    JOIN attribute_namespaces ns on ad.namespace_id = ns.id
    WHERE ns.id = $1 
)
INSERT OR REPLACE INTO attribute_fqns (id, namespace_id, attribute_id, value_id, fqn)
SELECT
    COALESCE(
        (
            SELECT af.id
            FROM attribute_fqns af
            WHERE af.namespace_id IS nf.namespace_id
              AND af.attribute_id IS nf.attribute_id
              AND af.value_id IS nf.value_id
        ),
        gen_random_uuid()
    ),
    nf.namespace_id,
    nf.attribute_id,
    nf.value_id,
    nf.fqn
FROM new_fqns_cte nf
RETURNING
    COALESCE(namespace_id, '') AS namespace_id,
    COALESCE(attribute_id, '') AS attribute_id,
    COALESCE(value_id, '') AS value_id,
    fqn
`

type UpsertAttributeNamespaceFqnRow struct {
	NamespaceID string `json:"namespace_id"`
	AttributeID string `json:"attribute_id"`
	ValueID     string `json:"value_id"`
	Fqn         string `json:"fqn"`
}

// UpsertAttributeNamespaceFqn
//
//	WITH new_fqns_cte AS (
//	    -- get namespace fqns
//	    SELECT
//	        ns.id as namespace_id,
//	        NULL as attribute_id,
//	        NULL as value_id,
//	        CONCAT('https://', ns.name) AS fqn
//	    FROM attribute_namespaces ns
//	    WHERE ns.id = $1
//	    UNION
//	    -- get attribute definition fqns
//	    SELECT
//	        ns.id as namespace_id,
//	        ad.id as attribute_id,
//	        NULL as value_id,
//	        CONCAT('https://', ns.name, '/attr/', ad.name) AS fqn
//	    FROM attribute_definitions ad
//	    JOIN attribute_namespaces ns on ad.namespace_id = ns.id
//	    WHERE ns.id = $1
//	    UNION
//	    -- get attribute value fqns
//	    SELECT
//	        ns.id as namespace_id,
//	        ad.id as attribute_id,
//	        av.id as value_id,
//	        CONCAT('https://', ns.name, '/attr/', ad.name, '/value/', av.value) AS fqn
//	    FROM attribute_values av
//	    JOIN attribute_definitions ad on av.attribute_definition_id = ad.id
//	    JOIN attribute_namespaces ns on ad.namespace_id = ns.id
//	    WHERE ns.id = $1
//	)
//	INSERT OR REPLACE INTO attribute_fqns (id, namespace_id, attribute_id, value_id, fqn)
//	SELECT
//	    COALESCE(
//	        (
//	            SELECT af.id
//	            FROM attribute_fqns af
//	            WHERE af.namespace_id IS nf.namespace_id
//	              AND af.attribute_id IS nf.attribute_id
//	              AND af.value_id IS nf.value_id
//	        ),
//	        gen_random_uuid()
//	    ),
//	    nf.namespace_id,
//	    nf.attribute_id,
//	    nf.value_id,
//	    nf.fqn
//	FROM new_fqns_cte nf
//	RETURNING
//	    COALESCE(namespace_id, '') AS namespace_id,
//	    COALESCE(attribute_id, '') AS attribute_id,
//	    COALESCE(value_id, '') AS value_id,
//	    fqn
func (q *Queries) UpsertAttributeNamespaceFqn(ctx context.Context, namespaceID string) ([]UpsertAttributeNamespaceFqnRow, error) {
	rows, err := q.db.QueryContext(ctx, upsertAttributeNamespaceFqn, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertAttributeNamespaceFqnRow
	for rows.Next() {
		var i UpsertAttributeNamespaceFqnRow
		if err := rows.Scan(
			&i.NamespaceID,
			&i.AttributeID,
			&i.ValueID,
			&i.Fqn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttributeValueFqn = `-- name: UpsertAttributeValueFqn :many

WITH new_fqns_cte AS (
    -- get attribute value fqns
    SELECT
        ns.id AS namespace_id,
        ad.id AS attribute_id,
        av.id AS value_id,
        CONCAT('https://', ns.name, '/attr/', ad.name, '/value/', av.value) AS fqn
    FROM attribute_values av
    INNER JOIN attribute_definitions AS ad ON av.attribute_definition_id = ad.id
    INNER JOIN attribute_namespaces AS ns ON ad.namespace_id = ns.id
    WHERE av.id = $1 
)

INSERT OR REPLACE INTO attribute_fqns (id, namespace_id, attribute_id, value_id, fqn)
SELECT
    COALESCE(
        (
            SELECT af.id
            FROM attribute_fqns af
            WHERE af.namespace_id IS nf.namespace_id
              AND af.attribute_id IS nf.attribute_id
              AND af.value_id IS nf.value_id
        ),
        gen_random_uuid()
    ),
    nf.namespace_id,
    nf.attribute_id,
    nf.value_id,
    nf.fqn
FROM new_fqns_cte nf
RETURNING
    COALESCE(namespace_id, '') AS namespace_id,
    COALESCE(attribute_id, '') AS attribute_id,
    COALESCE(value_id, '') AS value_id,
    fqn
`

type UpsertAttributeValueFqnRow struct {
	NamespaceID string `json:"namespace_id"`
	AttributeID string `json:"attribute_id"`
	ValueID     string `json:"value_id"`
	Fqn         string `json:"fqn"`
}

// --------------------------------------------------------------
// ATTRIBUTE FQN
// --------------------------------------------------------------
//
//	WITH new_fqns_cte AS (
//	    -- get attribute value fqns
//	    SELECT
//	        ns.id AS namespace_id,
//	        ad.id AS attribute_id,
//	        av.id AS value_id,
//	        CONCAT('https://', ns.name, '/attr/', ad.name, '/value/', av.value) AS fqn
//	    FROM attribute_values av
//	    INNER JOIN attribute_definitions AS ad ON av.attribute_definition_id = ad.id
//	    INNER JOIN attribute_namespaces AS ns ON ad.namespace_id = ns.id
//	    WHERE av.id = $1
//	)
//
//	INSERT OR REPLACE INTO attribute_fqns (id, namespace_id, attribute_id, value_id, fqn)
//	SELECT
//	    COALESCE(
//	        (
//	            SELECT af.id
//	            FROM attribute_fqns af
//	            WHERE af.namespace_id IS nf.namespace_id
//	              AND af.attribute_id IS nf.attribute_id
//	              AND af.value_id IS nf.value_id
//	        ),
//	        gen_random_uuid()
//	    ),
//	    nf.namespace_id,
//	    nf.attribute_id,
//	    nf.value_id,
//	    nf.fqn
//	FROM new_fqns_cte nf
//	RETURNING
//	    COALESCE(namespace_id, '') AS namespace_id,
//	    COALESCE(attribute_id, '') AS attribute_id,
//	    COALESCE(value_id, '') AS value_id,
//	    fqn
func (q *Queries) UpsertAttributeValueFqn(ctx context.Context, valueID string) ([]UpsertAttributeValueFqnRow, error) {
	rows, err := q.db.QueryContext(ctx, upsertAttributeValueFqn, valueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertAttributeValueFqnRow
	for rows.Next() {
		var i UpsertAttributeValueFqnRow
		if err := rows.Scan(
			&i.NamespaceID,
			&i.AttributeID,
			&i.ValueID,
			&i.Fqn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
