// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: key_management.sql

package dbsqlite

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createProviderConfig = `-- name: CreateProviderConfig :one

WITH inserted AS (
  INSERT INTO provider_config (id, provider_name, manager, config, metadata, created_at, updated_at)
  VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now'),
    STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')
  )
  RETURNING id, provider_name, manager, config, metadata, created_at, updated_at
)
SELECT 
  id,
  provider_name,
  manager,
  config,
  JSON_STRIP_NULLS(
    JSON_BUILD_OBJECT(
      'labels', json_extract(metadata, '$.labels'),         
      'created_at', created_at,               
      'updated_at', updated_at                
    )
  ) AS metadata
FROM inserted
`

type CreateProviderConfigParams struct {
	ProviderName string         `json:"provider_name"`
	Manager      sql.NullString `json:"manager"`
	Config       sql.NullString `json:"config"`
	Metadata     sql.NullString `json:"metadata"`
}

type CreateProviderConfigRow struct {
	ID           string          `json:"id"`
	ProviderName string          `json:"provider_name"`
	Manager      sql.NullString  `json:"manager"`
	Config       sql.NullString  `json:"config"`
	Metadata     json.RawMessage `json:"metadata"`
}

// --------------------------------------------------------------
// Provider Config
// --------------------------------------------------------------
//
//	WITH inserted AS (
//	  INSERT INTO provider_config (provider_name, manager, config, metadata)
//	  VALUES ($1, $2, $3, $4)
//	  RETURNING id, provider_name, manager, config, metadata, created_at, updated_at
//	)
//	SELECT
//	  id,
//	  provider_name,
//	  manager,
//	  config,
//	  JSON_STRIP_NULLS(
//	    JSON_BUILD_OBJECT(
//	      'labels', json_extract(metadata, '$.labels'),
//	      'created_at', created_at,
//	      'updated_at', updated_at
//	    )
//	  ) AS metadata
//	FROM inserted
func (q *Queries) CreateProviderConfig(ctx context.Context, arg CreateProviderConfigParams) (CreateProviderConfigRow, error) {
	row := q.db.QueryRowContext(ctx, createProviderConfig,
		arg.ProviderName,
		arg.Manager,
		arg.Config,
		arg.Metadata,
	)
	var i CreateProviderConfigRow
	err := row.Scan(
		&i.ID,
		&i.ProviderName,
		&i.Manager,
		&i.Config,
		&i.Metadata,
	)
	return i, err
}

const deleteProviderConfig = `-- name: DeleteProviderConfig :execrows
DELETE FROM provider_config 
WHERE id = $1
`

// DeleteProviderConfig
//
//	DELETE FROM provider_config
//	WHERE id = $1
func (q *Queries) DeleteProviderConfig(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProviderConfig, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProviderConfig = `-- name: GetProviderConfig :one
SELECT 
    pc.id,
    pc.provider_name,
    pc.manager,
    pc.config,
    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(pc.metadata, '$.labels'), 'created_at', pc.created_at, 'updated_at', pc.updated_at)) AS metadata
FROM provider_config AS pc
WHERE ($1 IS NULL OR pc.id = $1)
  AND ($2 IS NULL OR pc.provider_name = $2)
  AND ($3 IS NULL OR pc.manager = $3)
`

type GetProviderConfigParams struct {
	ID      interface{} `json:"id"`
	Name    interface{} `json:"name"`
	Manager interface{} `json:"manager"`
}

type GetProviderConfigRow struct {
	ID           string          `json:"id"`
	ProviderName string          `json:"provider_name"`
	Manager      sql.NullString  `json:"manager"`
	Config       sql.NullString  `json:"config"`
	Metadata     json.RawMessage `json:"metadata"`
}

// GetProviderConfig
//
//	SELECT
//	    pc.id,
//	    pc.provider_name,
//	    pc.manager,
//	    pc.config,
//	    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(pc.metadata, '$.labels'), 'created_at', pc.created_at, 'updated_at', pc.updated_at)) AS metadata
//	FROM provider_config AS pc
//	WHERE ($1 IS NULL OR pc.id = $1)
//	  AND ($2 IS NULL OR pc.provider_name = $2)
//	  AND ($3 IS NULL OR pc.manager = $3)
func (q *Queries) GetProviderConfig(ctx context.Context, arg GetProviderConfigParams) (GetProviderConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getProviderConfig, arg.ID, arg.Name, arg.Manager)
	var i GetProviderConfigRow
	err := row.Scan(
		&i.ID,
		&i.ProviderName,
		&i.Manager,
		&i.Config,
		&i.Metadata,
	)
	return i, err
}

const listProviderConfigs = `-- name: ListProviderConfigs :many
WITH counted AS (
    SELECT COUNT(pc.id) AS total 
    FROM provider_config pc
)
SELECT 
    pc.id,
    pc.provider_name,
    pc.manager,
    pc.config,
    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(pc.metadata, '$.labels'), 'created_at', pc.created_at, 'updated_at', pc.updated_at)) AS metadata,
    counted.total
FROM provider_config AS pc
CROSS JOIN counted
ORDER BY pc.created_at DESC
LIMIT $2 
OFFSET $1
`

type ListProviderConfigsParams struct {
	Offset int32 `json:"offset_"`
	Limit  int32 `json:"limit_"`
}

type ListProviderConfigsRow struct {
	ID           string          `json:"id"`
	ProviderName string          `json:"provider_name"`
	Manager      sql.NullString  `json:"manager"`
	Config       sql.NullString  `json:"config"`
	Metadata     json.RawMessage `json:"metadata"`
	Total        int64           `json:"total"`
}

// ListProviderConfigs
//
//	WITH counted AS (
//	    SELECT COUNT(pc.id) AS total
//	    FROM provider_config pc
//	)
//	SELECT
//	    pc.id,
//	    pc.provider_name,
//	    pc.manager,
//	    pc.config,
//	    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(pc.metadata, '$.labels'), 'created_at', pc.created_at, 'updated_at', pc.updated_at)) AS metadata,
//	    counted.total
//	FROM provider_config AS pc
//	CROSS JOIN counted
//	ORDER BY pc.created_at DESC
//	LIMIT $2
//	OFFSET $1
func (q *Queries) ListProviderConfigs(ctx context.Context, arg ListProviderConfigsParams) ([]ListProviderConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProviderConfigs, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderConfigsRow
	for rows.Next() {
		var i ListProviderConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderName,
			&i.Manager,
			&i.Config,
			&i.Metadata,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderConfig = `-- name: UpdateProviderConfig :execrows
UPDATE provider_config
SET
    provider_name = COALESCE($2, provider_name),
    manager = COALESCE($3, manager),
    config = COALESCE($4, config),
    metadata = COALESCE($5, metadata),
    updated_at = STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now', '+0.001 seconds')
WHERE id = $1
`

type UpdateProviderConfigParams struct {
	ID           string         `json:"id"`
	ProviderName sql.NullString `json:"provider_name"`
	Manager      sql.NullString `json:"manager"`
	Config       sql.NullString `json:"config"`
	Metadata     sql.NullString `json:"metadata"`
}

// UpdateProviderConfig
//
//	UPDATE provider_config
//	SET
//	    provider_name = COALESCE($2, provider_name),
//	    manager = COALESCE($3, manager),
//	    config = COALESCE($4, config),
//	    metadata = COALESCE($5, metadata)
//	WHERE id = $1
func (q *Queries) UpdateProviderConfig(ctx context.Context, arg UpdateProviderConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProviderConfig,
		arg.ID,
		arg.ProviderName,
		arg.Manager,
		arg.Config,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
