// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlite

import (
	"database/sql"
)

type Action struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	IsStandard sql.NullBool   `json:"is_standard"`
	Metadata   sql.NullString `json:"metadata"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type AttributeDefinition struct {
	ID             string         `json:"id"`
	NamespaceID    sql.NullString `json:"namespace_id"`
	Name           string         `json:"name"`
	Rule           sql.NullString `json:"rule"`
	Metadata       sql.NullString `json:"metadata"`
	Active         sql.NullBool   `json:"active"`
	ValuesOrder    sql.NullString `json:"values_order"`
	AllowTraversal sql.NullBool   `json:"allow_traversal"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type AttributeDefinitionKeyAccessGrant struct {
	AttributeDefinitionID sql.NullString `json:"attribute_definition_id"`
	KeyAccessServerID     sql.NullString `json:"key_access_server_id"`
}

type AttributeDefinitionPublicKeyMap struct {
	DefinitionID         sql.NullString `json:"definition_id"`
	KeyAccessServerKeyID sql.NullString `json:"key_access_server_key_id"`
}

type AttributeFqn struct {
	ID          string         `json:"id"`
	Fqn         string         `json:"fqn"`
	NamespaceID sql.NullString `json:"namespace_id"`
	AttributeID sql.NullString `json:"attribute_id"`
	ValueID     sql.NullString `json:"value_id"`
}

type AttributeNamespace struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Metadata  sql.NullString `json:"metadata"`
	Active    sql.NullBool   `json:"active"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type AttributeNamespaceKeyAccessGrant struct {
	NamespaceID       sql.NullString `json:"namespace_id"`
	KeyAccessServerID sql.NullString `json:"key_access_server_id"`
}

type AttributeNamespacePublicKeyMap struct {
	NamespaceID          sql.NullString `json:"namespace_id"`
	KeyAccessServerKeyID sql.NullString `json:"key_access_server_key_id"`
}

type AttributeValue struct {
	ID                    string         `json:"id"`
	AttributeDefinitionID sql.NullString `json:"attribute_definition_id"`
	Value                 string         `json:"value"`
	Metadata              sql.NullString `json:"metadata"`
	Active                sql.NullBool   `json:"active"`
	Members               sql.NullString `json:"members"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
}

type AttributeValueKeyAccessGrant struct {
	AttributeValueID  sql.NullString `json:"attribute_value_id"`
	KeyAccessServerID sql.NullString `json:"key_access_server_id"`
}

type AttributeValuePublicKeyMap struct {
	ValueID              sql.NullString `json:"value_id"`
	KeyAccessServerKeyID sql.NullString `json:"key_access_server_key_id"`
}

type BaseKey struct {
	ID                   string         `json:"id"`
	KeyAccessServerKeyID sql.NullString `json:"key_access_server_key_id"`
}

type KeyAccessServer struct {
	ID         string         `json:"id"`
	Uri        string         `json:"uri"`
	PublicKey  sql.NullString `json:"public_key"`
	Metadata   sql.NullString `json:"metadata"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	Name       sql.NullString `json:"name"`
	SourceType sql.NullString `json:"source_type"`
}

type KeyAccessServerKey struct {
	ID                string         `json:"id"`
	KeyAccessServerID sql.NullString `json:"key_access_server_id"`
	KeyAlgorithm      sql.NullInt32  `json:"key_algorithm"`
	KeyID             sql.NullString `json:"key_id"`
	KeyStatus         sql.NullInt32  `json:"key_status"`
	KeyMode           sql.NullInt32  `json:"key_mode"`
	PublicKeyCtx      sql.NullString `json:"public_key_ctx"`
	PrivateKeyCtx     sql.NullString `json:"private_key_ctx"`
	Expiration        sql.NullTime   `json:"expiration"`
	ProviderConfigID  sql.NullString `json:"provider_config_id"`
	Metadata          sql.NullString `json:"metadata"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	Legacy            sql.NullBool   `json:"legacy"`
}

type ObligationDefinition struct {
	ID          string         `json:"id"`
	NamespaceID sql.NullString `json:"namespace_id"`
	Name        string         `json:"name"`
	Metadata    sql.NullString `json:"metadata"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ObligationFulfiller struct {
	ID                string         `json:"id"`
	ObligationValueID sql.NullString `json:"obligation_value_id"`
	Conditionals      sql.NullString `json:"conditionals"`
	Metadata          sql.NullString `json:"metadata"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type ObligationTrigger struct {
	ID                string         `json:"id"`
	ObligationValueID sql.NullString `json:"obligation_value_id"`
	ActionID          sql.NullString `json:"action_id"`
	AttributeValueID  sql.NullString `json:"attribute_value_id"`
	ClientID          sql.NullString `json:"client_id"`
	Metadata          sql.NullString `json:"metadata"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type ObligationValuesStandard struct {
	ID                     string         `json:"id"`
	ObligationDefinitionID sql.NullString `json:"obligation_definition_id"`
	Value                  string         `json:"value"`
	Metadata               sql.NullString `json:"metadata"`
	CreatedAt              sql.NullTime   `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
}

type ProviderConfig struct {
	ID           string         `json:"id"`
	ProviderName string         `json:"provider_name"`
	Manager      sql.NullString `json:"manager"`
	Config       sql.NullString `json:"config"`
	Metadata     sql.NullString `json:"metadata"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type RegisteredResource struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type RegisteredResourceActionAttributeValue struct {
	ID                        string         `json:"id"`
	RegisteredResourceValueID sql.NullString `json:"registered_resource_value_id"`
	ActionID                  sql.NullString `json:"action_id"`
	AttributeValueID          sql.NullString `json:"attribute_value_id"`
	CreatedAt                 sql.NullTime   `json:"created_at"`
	UpdatedAt                 sql.NullTime   `json:"updated_at"`
}

type RegisteredResourceValue struct {
	ID                   string         `json:"id"`
	RegisteredResourceID sql.NullString `json:"registered_resource_id"`
	Value                string         `json:"value"`
	Metadata             sql.NullString `json:"metadata"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type ResourceMapping struct {
	ID               string         `json:"id"`
	AttributeValueID sql.NullString `json:"attribute_value_id"`
	Terms            sql.NullString `json:"terms"`
	Metadata         sql.NullString `json:"metadata"`
	GroupID          sql.NullString `json:"group_id"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type ResourceMappingGroup struct {
	ID          string         `json:"id"`
	NamespaceID sql.NullString `json:"namespace_id"`
	Name        sql.NullString `json:"name"`
	Metadata    sql.NullString `json:"metadata"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type SubjectConditionSet struct {
	ID             string         `json:"id"`
	Condition      sql.NullString `json:"condition"`
	Metadata       sql.NullString `json:"metadata"`
	SelectorValues sql.NullString `json:"selector_values"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type SubjectMapping struct {
	ID                    string         `json:"id"`
	AttributeValueID      sql.NullString `json:"attribute_value_id"`
	SubjectConditionSetID sql.NullString `json:"subject_condition_set_id"`
	Metadata              sql.NullString `json:"metadata"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
}

type SubjectMappingAction struct {
	SubjectMappingID sql.NullString `json:"subject_mapping_id"`
	ActionID         sql.NullString `json:"action_id"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}
