// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: obligations.sql

package dbsqlite

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const createObligation = `-- name: CreateObligation :one

WITH inserted_obligation AS (
    INSERT INTO obligation_definitions (id, namespace_id, name, metadata, created_at, updated_at)
    VALUES (
        gen_random_uuid(),
        COALESCE(
            $1,
            (SELECT fqns.namespace_id FROM attribute_fqns fqns
             WHERE fqns.fqn = $2 AND $1 IS NULL)
        ),
        $3,
        $4,
        STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now'),
        STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')
    )
    RETURNING id, namespace_id, name, metadata
),
inserted_values AS (
    INSERT INTO obligation_values_standard (id, obligation_definition_id, value, created_at, updated_at)
    SELECT
        gen_random_uuid(),
        io.id,
        vals.value,
        STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now'),
        STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')
    FROM inserted_obligation io
    CROSS JOIN json_each($5) AS vals(value)
    WHERE $5 IS NOT NULL
    RETURNING id, obligation_definition_id, value
)
SELECT
    io.id,
    io.name,
    io.metadata,
    JSON_BUILD_OBJECT(
        'id', n.id,
        'name', n.name,
        'fqn', fqns.fqn
    ) as namespace,
    COALESCE(
        JSON_AGG(
            CASE
                WHEN iv.id IS NOT NULL THEN JSON_BUILD_OBJECT(
                    'id', iv.id,
                    'value', iv.value
                )
            END
        ),
        '[]'
    ) as "values"
FROM inserted_obligation io
JOIN attribute_namespaces n ON io.namespace_id = n.id
LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
LEFT JOIN inserted_values iv ON iv.obligation_definition_id = io.id
GROUP BY io.id, io.name, io.metadata, n.id, fqns.fqn
`

type CreateObligationParams struct {
	NamespaceID  interface{}           `json:"namespace_id"`
	NamespaceFqn sql.NullString        `json:"namespace_fqn"`
	Name         string                `json:"name"`
	Metadata     sql.NullString        `json:"metadata"`
	Values       pqtype.NullRawMessage `json:"values"`
}

type CreateObligationRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Metadata  sql.NullString  `json:"metadata"`
	Namespace json.RawMessage `json:"namespace"`
	Values    interface{}     `json:"values"`
}

// --------------------------------------------------------------
// OBLIGATIONS
// --------------------------------------------------------------
//
//	WITH inserted_obligation AS (
//	    INSERT INTO obligation_definitions (namespace_id, name, metadata)
//	    VALUES (
//	        COALESCE(
//	            $1,
//	            (SELECT fqns.namespace_id FROM attribute_fqns fqns
//	             WHERE fqns.fqn = $2 AND $1 IS NULL)
//	        ),
//	        $3,
//	        $4
//	    )
//	    RETURNING id, namespace_id, name, metadata
//	),
//	inserted_values AS (
//	    INSERT INTO obligation_values_standard (obligation_definition_id, value)
//	    SELECT io.id, vals.value
//	    FROM inserted_obligation io
//	    CROSS JOIN json_each($5) AS vals(value)
//	    WHERE $5 IS NOT NULL
//	    RETURNING id, obligation_definition_id, value
//	)
//	SELECT
//	    io.id,
//	    io.name,
//	    io.metadata,
//	    JSON_BUILD_OBJECT(
//	        'id', n.id,
//	        'name', n.name,
//	        'fqn', fqns.fqn
//	    ) as namespace,
//	    COALESCE(
//	        JSON_AGG(
//	            CASE
//	                WHEN iv.id IS NOT NULL THEN JSON_BUILD_OBJECT(
//	                    'id', iv.id,
//	                    'value', iv.value
//	                )
//	            END
//	        ),
//	        '[]'
//	    ) as "values"
//	FROM inserted_obligation io
//	JOIN attribute_namespaces n ON io.namespace_id = n.id
//	LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
//	LEFT JOIN inserted_values iv ON iv.obligation_definition_id = io.id
//	GROUP BY io.id, io.name, io.metadata, n.id, fqns.fqn
func (q *Queries) CreateObligation(ctx context.Context, arg CreateObligationParams) (CreateObligationRow, error) {
	row := q.db.QueryRowContext(ctx, createObligation,
		arg.NamespaceID,
		arg.NamespaceFqn,
		arg.Name,
		arg.Metadata,
		arg.Values,
	)
	var i CreateObligationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.Namespace,
		&i.Values,
	)
	return i, err
}

const createObligationTrigger = `-- name: CreateObligationTrigger :one

WITH ov_id AS (
    SELECT ov.id, od.namespace_id
    FROM obligation_values_standard ov
    JOIN obligation_definitions od ON ov.obligation_definition_id = od.id
    WHERE $1 IS NOT NULL AND ov.id = $1
),
a_id AS (
    SELECT a.id
    FROM actions a
    WHERE
        ($2 IS NOT NULL AND a.id = $2)
        OR
        ($3 IS NOT NULL AND a.name = $3)
),
av_id AS (
    SELECT av.id
    FROM attribute_values av
    JOIN attribute_definitions ad ON av.attribute_definition_id = ad.id
    LEFT JOIN attribute_fqns fqns ON fqns.value_id = av.id
    WHERE
        (($4 IS NOT NULL AND av.id = $4)
        OR
        ($5 IS NOT NULL AND fqns.fqn = $5))
        AND ad.namespace_id = (SELECT namespace_id FROM ov_id)
),
inserted AS (
    INSERT INTO obligation_triggers (id, obligation_value_id, action_id, attribute_value_id, metadata, client_id, created_at, updated_at)
    SELECT
        gen_random_uuid(),
        (SELECT id FROM ov_id),
        (SELECT id FROM a_id),
        (SELECT id FROM av_id),
        $6,
        $7,
        STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now'),
        STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')
    RETURNING id, obligation_value_id, action_id, attribute_value_id, metadata, created_at, updated_at, client_id
)
SELECT
    JSON_STRIP_NULLS(
        JSON_BUILD_OBJECT(
            'labels', json_extract(i.metadata, '$.labels'),
            'created_at', i.created_at,
            'updated_at', i.updated_at
        )
    ) AS metadata,
    JSON_STRIP_NULLS(
        JSON_BUILD_OBJECT(
            'id', i.id,
            'obligation_value', JSON_BUILD_OBJECT(
                'id', ov.id,
                'value', ov.value,
                'obligation', JSON_BUILD_OBJECT(
                    'id', od.id,
                    'name', od.name,
                    'namespace', JSON_BUILD_OBJECT(
                        'id', n.id,
                        'name', n.name,
                        'fqn', COALESCE(ns_fqns.fqn, '')
                    )
                )
            ),
            'action', JSON_BUILD_OBJECT(
                'id', a.id,
                'name', a.name
            ),
            'attribute_value', JSON_BUILD_OBJECT(
                'id', av.id,
                'value', av.value,
                'fqn', COALESCE(av_fqns.fqn, '')
            ),
            'context', CASE
                WHEN i.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
                    JSON_BUILD_OBJECT(
                        'pep', JSON_BUILD_OBJECT(
                            'client_id', i.client_id
                        )
                    ))
                ELSE '[]'
            END
        )
    ) as "trigger"
FROM inserted i
JOIN obligation_values_standard ov ON i.obligation_value_id = ov.id
JOIN obligation_definitions od ON ov.obligation_definition_id = od.id
JOIN attribute_namespaces n ON od.namespace_id = n.id
LEFT JOIN attribute_fqns ns_fqns ON ns_fqns.namespace_id = n.id AND ns_fqns.attribute_id IS NULL AND ns_fqns.value_id IS NULL
JOIN actions a ON i.action_id = a.id
JOIN attribute_values av ON i.attribute_value_id = av.id
LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
`

type CreateObligationTriggerParams struct {
	ObligationValueID interface{}    `json:"obligation_value_id"`
	ActionID          interface{}    `json:"action_id"`
	ActionName        interface{}    `json:"action_name"`
	AttributeValueID  interface{}    `json:"attribute_value_id"`
	AttributeValueFqn interface{}    `json:"attribute_value_fqn"`
	Metadata          sql.NullString `json:"metadata"`
	ClientID          sql.NullString `json:"client_id"`
}

type CreateObligationTriggerRow struct {
	Metadata json.RawMessage `json:"metadata"`
	Trigger  json.RawMessage `json:"trigger"`
}

// --------------------------------------------------------------
// OBLIGATION TRIGGERS
// --------------------------------------------------------------
// Gets the attribute value, but also ensures that the attribute value belongs to the same namespace as the obligation, to which the obligation value belongs
//
//	WITH ov_id AS (
//	    SELECT ov.id, od.namespace_id
//	    FROM obligation_values_standard ov
//	    JOIN obligation_definitions od ON ov.obligation_definition_id = od.id
//	    WHERE $1 IS NOT NULL AND ov.id = $1
//	),
//	a_id AS (
//	    SELECT a.id
//	    FROM actions a
//	    WHERE
//	        ($2 IS NOT NULL AND a.id = $2)
//	        OR
//	        ($3 IS NOT NULL AND a.name = $3)
//	),
//	av_id AS (
//	    SELECT av.id
//	    FROM attribute_values av
//	    JOIN attribute_definitions ad ON av.attribute_definition_id = ad.id
//	    LEFT JOIN attribute_fqns fqns ON fqns.value_id = av.id
//	    WHERE
//	        (($4 IS NOT NULL AND av.id = $4)
//	        OR
//	        ($5 IS NOT NULL AND fqns.fqn = $5))
//	        AND ad.namespace_id = (SELECT namespace_id FROM ov_id)
//	),
//	inserted AS (
//	    INSERT INTO obligation_triggers (obligation_value_id, action_id, attribute_value_id, metadata, client_id)
//	    SELECT
//	        (SELECT id FROM ov_id),
//	        (SELECT id FROM a_id),
//	        (SELECT id FROM av_id),
//	        $6,
//	        $7
//	    RETURNING id, obligation_value_id, action_id, attribute_value_id, metadata, created_at, updated_at, client_id
//	)
//	SELECT
//	    JSON_STRIP_NULLS(
//	        JSON_BUILD_OBJECT(
//	            'labels', json_extract(i.metadata, '$.labels'),
//	            'created_at', i.created_at,
//	            'updated_at', i.updated_at
//	        )
//	    ) AS metadata,
//	    JSON_STRIP_NULLS(
//	        JSON_BUILD_OBJECT(
//	            'id', i.id,
//	            'obligation_value', JSON_BUILD_OBJECT(
//	                'id', ov.id,
//	                'value', ov.value,
//	                'obligation', JSON_BUILD_OBJECT(
//	                    'id', od.id,
//	                    'name', od.name,
//	                    'namespace', JSON_BUILD_OBJECT(
//	                        'id', n.id,
//	                        'name', n.name,
//	                        'fqn', COALESCE(ns_fqns.fqn, '')
//	                    )
//	                )
//	            ),
//	            'action', JSON_BUILD_OBJECT(
//	                'id', a.id,
//	                'name', a.name
//	            ),
//	            'attribute_value', JSON_BUILD_OBJECT(
//	                'id', av.id,
//	                'value', av.value,
//	                'fqn', COALESCE(av_fqns.fqn, '')
//	            ),
//	            'context', CASE
//	                WHEN i.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
//	                    JSON_BUILD_OBJECT(
//	                        'pep', JSON_BUILD_OBJECT(
//	                            'client_id', i.client_id
//	                        )
//	                    ))
//	                ELSE '[]'
//	            END
//	        )
//	    ) as "trigger"
//	FROM inserted i
//	JOIN obligation_values_standard ov ON i.obligation_value_id = ov.id
//	JOIN obligation_definitions od ON ov.obligation_definition_id = od.id
//	JOIN attribute_namespaces n ON od.namespace_id = n.id
//	LEFT JOIN attribute_fqns ns_fqns ON ns_fqns.namespace_id = n.id AND ns_fqns.attribute_id IS NULL AND ns_fqns.value_id IS NULL
//	JOIN actions a ON i.action_id = a.id
//	JOIN attribute_values av ON i.attribute_value_id = av.id
//	LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
func (q *Queries) CreateObligationTrigger(ctx context.Context, arg CreateObligationTriggerParams) (CreateObligationTriggerRow, error) {
	row := q.db.QueryRowContext(ctx, createObligationTrigger,
		arg.ObligationValueID,
		arg.ActionID,
		arg.ActionName,
		arg.AttributeValueID,
		arg.AttributeValueFqn,
		arg.Metadata,
		arg.ClientID,
	)
	var i CreateObligationTriggerRow
	err := row.Scan(&i.Metadata, &i.Trigger)
	return i, err
}

const createObligationValue = `-- name: CreateObligationValue :one

WITH obligation_lookup AS (
    SELECT od.id, od.name, od.metadata
    FROM obligation_definitions od
    LEFT JOIN attribute_namespaces n ON od.namespace_id = n.id
    LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
    WHERE
        -- lookup by obligation id OR by namespace fqn + obligation name
        (
            -- lookup by obligation id
            ($1 IS NOT NULL AND od.id = $1)
            OR
            -- lookup by namespace fqn + obligation name
            ($2 IS NOT NULL AND $3 IS NOT NULL 
             AND fqns.fqn = $2 AND od.name = $3)
        )
),
inserted_value AS (
    INSERT INTO obligation_values_standard (id, obligation_definition_id, value, metadata, created_at, updated_at)
    SELECT
        gen_random_uuid(),
        ol.id,
        $4,
        $5,
        STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now'),
        STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')
    FROM obligation_lookup ol
    RETURNING id, obligation_definition_id, value, metadata
)
SELECT
    iv.id,
    ol.name,
    ol.id as obligation_id,
    JSON_BUILD_OBJECT(
        'id', n.id,
        'name', n.name,
        'fqn', fqns.fqn
    ) as namespace,
    iv.metadata as metadata
FROM inserted_value iv
JOIN obligation_lookup ol ON ol.id = iv.obligation_definition_id
JOIN obligation_definitions od ON od.id = ol.id
JOIN attribute_namespaces n ON od.namespace_id = n.id
LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
`

type CreateObligationValueParams struct {
	ID           interface{}    `json:"id"`
	NamespaceFqn interface{}    `json:"namespace_fqn"`
	Name         interface{}    `json:"name"`
	Value        string         `json:"value"`
	Metadata     sql.NullString `json:"metadata"`
}

type CreateObligationValueRow struct {
	ID           string          `json:"id"`
	Name         string          `json:"name"`
	ObligationID string          `json:"obligation_id"`
	Namespace    json.RawMessage `json:"namespace"`
	Metadata     sql.NullString  `json:"metadata"`
}

// --------------------------------------------------------------
// OBLIGATION VALUES
// --------------------------------------------------------------
//
//	WITH obligation_lookup AS (
//	    SELECT od.id, od.name, od.metadata
//	    FROM obligation_definitions od
//	    LEFT JOIN attribute_namespaces n ON od.namespace_id = n.id
//	    LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
//	    WHERE
//	        -- lookup by obligation id OR by namespace fqn + obligation name
//	        (
//	            -- lookup by obligation id
//	            ($1 IS NOT NULL AND od.id = $1)
//	            OR
//	            -- lookup by namespace fqn + obligation name
//	            ($2 IS NOT NULL AND $3 IS NOT NULL
//	             AND fqns.fqn = $2 AND od.name = $3)
//	        )
//	),
//	inserted_value AS (
//	    INSERT INTO obligation_values_standard (obligation_definition_id, value, metadata)
//	    SELECT ol.id, $4, $5
//	    FROM obligation_lookup ol
//	    RETURNING id, obligation_definition_id, value, metadata
//	)
//	SELECT
//	    iv.id,
//	    ol.name,
//	    ol.id as obligation_id,
//	    JSON_BUILD_OBJECT(
//	        'id', n.id,
//	        'name', n.name,
//	        'fqn', fqns.fqn
//	    ) as namespace,
//	    iv.metadata as metadata
//	FROM inserted_value iv
//	JOIN obligation_lookup ol ON ol.id = iv.obligation_definition_id
//	JOIN obligation_definitions od ON od.id = ol.id
//	JOIN attribute_namespaces n ON od.namespace_id = n.id
//	LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
func (q *Queries) CreateObligationValue(ctx context.Context, arg CreateObligationValueParams) (CreateObligationValueRow, error) {
	row := q.db.QueryRowContext(ctx, createObligationValue,
		arg.ID,
		arg.NamespaceFqn,
		arg.Name,
		arg.Value,
		arg.Metadata,
	)
	var i CreateObligationValueRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ObligationID,
		&i.Namespace,
		&i.Metadata,
	)
	return i, err
}

const deleteAllObligationTriggersForValue = `-- name: DeleteAllObligationTriggersForValue :execrows
DELETE FROM obligation_triggers
WHERE obligation_value_id = $1
`

// DeleteAllObligationTriggersForValue
//
//	DELETE FROM obligation_triggers
//	WHERE obligation_value_id = $1
func (q *Queries) DeleteAllObligationTriggersForValue(ctx context.Context, obligationValueID sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllObligationTriggersForValue, obligationValueID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteObligation = `-- name: DeleteObligation :one
DELETE FROM obligation_definitions 
WHERE id IN (
    SELECT od.id
    FROM obligation_definitions od
    LEFT JOIN attribute_namespaces n ON od.namespace_id = n.id
    LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
    WHERE
        -- lookup by obligation id OR by namespace fqn + obligation name
        (
            -- lookup by obligation id
            ($1 IS NOT NULL AND od.id = $1)
            OR
            -- lookup by namespace fqn + obligation name
            ($2 IS NOT NULL AND $3 IS NOT NULL 
             AND fqns.fqn = $2 AND od.name = $3)
        )
)
RETURNING id
`

type DeleteObligationParams struct {
	ID           interface{} `json:"id"`
	NamespaceFqn interface{} `json:"namespace_fqn"`
	Name         interface{} `json:"name"`
}

// DeleteObligation
//
//	DELETE FROM obligation_definitions
//	WHERE id IN (
//	    SELECT od.id
//	    FROM obligation_definitions od
//	    LEFT JOIN attribute_namespaces n ON od.namespace_id = n.id
//	    LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
//	    WHERE
//	        -- lookup by obligation id OR by namespace fqn + obligation name
//	        (
//	            -- lookup by obligation id
//	            ($1 IS NOT NULL AND od.id = $1)
//	            OR
//	            -- lookup by namespace fqn + obligation name
//	            ($2 IS NOT NULL AND $3 IS NOT NULL
//	             AND fqns.fqn = $2 AND od.name = $3)
//	        )
//	)
//	RETURNING id
func (q *Queries) DeleteObligation(ctx context.Context, arg DeleteObligationParams) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteObligation, arg.ID, arg.NamespaceFqn, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteObligationTrigger = `-- name: DeleteObligationTrigger :one
DELETE FROM obligation_triggers
WHERE id = $1
RETURNING id
`

// DeleteObligationTrigger
//
//	DELETE FROM obligation_triggers
//	WHERE id = $1
//	RETURNING id
func (q *Queries) DeleteObligationTrigger(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteObligationTrigger, id)
	err := row.Scan(&id)
	return id, err
}

const deleteObligationValue = `-- name: DeleteObligationValue :one
DELETE FROM obligation_values_standard
WHERE id IN (
    SELECT ov.id
    FROM obligation_values_standard ov
    JOIN obligation_definitions od ON ov.obligation_definition_id = od.id
    LEFT JOIN attribute_namespaces n ON od.namespace_id = n.id
    LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
    WHERE
        -- lookup by value id OR by namespace fqn + obligation name + value name
        (
            -- lookup by value id
            ($1 IS NOT NULL AND ov.id = $1)
            OR
            -- lookup by namespace fqn + obligation name + value
            ($2 IS NOT NULL AND $3 IS NOT NULL AND $4 IS NOT NULL
             AND fqns.fqn = $2 AND od.name = $3 AND ov.value = $4)
        )
)
RETURNING id
`

type DeleteObligationValueParams struct {
	ID           interface{} `json:"id"`
	NamespaceFqn interface{} `json:"namespace_fqn"`
	Name         interface{} `json:"name"`
	Value        interface{} `json:"value"`
}

// DeleteObligationValue
//
//	DELETE FROM obligation_values_standard
//	WHERE id IN (
//	    SELECT ov.id
//	    FROM obligation_values_standard ov
//	    JOIN obligation_definitions od ON ov.obligation_definition_id = od.id
//	    LEFT JOIN attribute_namespaces n ON od.namespace_id = n.id
//	    LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
//	    WHERE
//	        -- lookup by value id OR by namespace fqn + obligation name + value name
//	        (
//	            -- lookup by value id
//	            ($1 IS NOT NULL AND ov.id = $1)
//	            OR
//	            -- lookup by namespace fqn + obligation name + value
//	            ($2 IS NOT NULL AND $3 IS NOT NULL AND $4 IS NOT NULL
//	             AND fqns.fqn = $2 AND od.name = $3 AND ov.value = $4)
//	        )
//	)
//	RETURNING id
func (q *Queries) DeleteObligationValue(ctx context.Context, arg DeleteObligationValueParams) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteObligationValue,
		arg.ID,
		arg.NamespaceFqn,
		arg.Name,
		arg.Value,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getObligation = `-- name: GetObligation :one
WITH obligation_triggers_agg AS (
    SELECT
        ot.obligation_value_id,
        JSON_AGG(
            JSON_BUILD_OBJECT(
                'id', ot.id,
                'action', JSON_BUILD_OBJECT(
                    'id', a.id,
                    'name', a.name
                ),
                'attribute_value', JSON_BUILD_OBJECT(
                    'id', av.id,
                    'value', av.value,
                    'fqn', COALESCE(av_fqns.fqn, '')
                ),
                'context', CASE
                    WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
                        JSON_BUILD_OBJECT(
                            'pep', JSON_BUILD_OBJECT(
                                'client_id', ot.client_id
                            )
                        )
                    )
                    ELSE '[]'
                END
            )
        ) as triggers
    FROM obligation_triggers ot
    JOIN actions a ON ot.action_id = a.id
    JOIN attribute_values av ON ot.attribute_value_id = av.id
    LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
    GROUP BY ot.obligation_value_id
)
SELECT
    od.id,
    od.name,
    JSON_BUILD_OBJECT(
        'id', n.id,
        'name', n.name,
        'fqn', fqns.fqn
    ) as namespace,
    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(od.metadata, '$.labels'), 'created_at', od.created_at,'updated_at', od.updated_at)) as metadata,
    JSON_AGG(
        CASE
            WHEN ov.id IS NOT NULL THEN JSON_BUILD_OBJECT(
                'id', ov.id,
                'value', ov.value,
                'triggers', COALESCE(ota.triggers, '[]')
            )
        END
    ) as "values"
FROM obligation_definitions od
JOIN attribute_namespaces n on od.namespace_id = n.id
LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
LEFT JOIN obligation_values_standard ov on od.id = ov.obligation_definition_id
LEFT JOIN obligation_triggers_agg ota on ov.id = ota.obligation_value_id
WHERE
    -- lookup by obligation id OR by namespace fqn + obligation name
    (
        -- lookup by obligation id
        ($1 IS NOT NULL AND od.id = $1)
        OR
        -- lookup by namespace fqn + obligation name
        ($2 IS NOT NULL AND $3 IS NOT NULL
         AND fqns.fqn = $2 AND od.name = $3)
    )
GROUP BY od.id, n.id, fqns.fqn
`

type GetObligationParams struct {
	ID           interface{} `json:"id"`
	NamespaceFqn interface{} `json:"namespace_fqn"`
	Name         interface{} `json:"name"`
}

type GetObligationRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Namespace json.RawMessage `json:"namespace"`
	Metadata  json.RawMessage `json:"metadata"`
	Values    json.RawMessage `json:"values"`
}

// GetObligation
//
//	WITH obligation_triggers_agg AS (
//	    SELECT
//	        ot.obligation_value_id,
//	        JSON_AGG(
//	            JSON_BUILD_OBJECT(
//	                'id', ot.id,
//	                'action', JSON_BUILD_OBJECT(
//	                    'id', a.id,
//	                    'name', a.name
//	                ),
//	                'attribute_value', JSON_BUILD_OBJECT(
//	                    'id', av.id,
//	                    'value', av.value,
//	                    'fqn', COALESCE(av_fqns.fqn, '')
//	                ),
//	                'context', CASE
//	                    WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
//	                        JSON_BUILD_OBJECT(
//	                            'pep', JSON_BUILD_OBJECT(
//	                                'client_id', ot.client_id
//	                            )
//	                        )
//	                    )
//	                    ELSE '[]'
//	                END
//	            )
//	        ) as triggers
//	    FROM obligation_triggers ot
//	    JOIN actions a ON ot.action_id = a.id
//	    JOIN attribute_values av ON ot.attribute_value_id = av.id
//	    LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
//	    GROUP BY ot.obligation_value_id
//	)
//	SELECT
//	    od.id,
//	    od.name,
//	    JSON_BUILD_OBJECT(
//	        'id', n.id,
//	        'name', n.name,
//	        'fqn', fqns.fqn
//	    ) as namespace,
//	    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(od.metadata, '$.labels'), 'created_at', od.created_at,'updated_at', od.updated_at)) as metadata,
//	    JSON_AGG(
//	        CASE
//	            WHEN ov.id IS NOT NULL THEN JSON_BUILD_OBJECT(
//	                'id', ov.id,
//	                'value', ov.value,
//	                'triggers', COALESCE(ota.triggers, '[]')
//	            )
//	        END
//	    ) as "values"
//	FROM obligation_definitions od
//	JOIN attribute_namespaces n on od.namespace_id = n.id
//	LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
//	LEFT JOIN obligation_values_standard ov on od.id = ov.obligation_definition_id
//	LEFT JOIN obligation_triggers_agg ota on ov.id = ota.obligation_value_id
//	WHERE
//	    -- lookup by obligation id OR by namespace fqn + obligation name
//	    (
//	        -- lookup by obligation id
//	        ($1 IS NOT NULL AND od.id = $1)
//	        OR
//	        -- lookup by namespace fqn + obligation name
//	        ($2 IS NOT NULL AND $3 IS NOT NULL
//	         AND fqns.fqn = $2 AND od.name = $3)
//	    )
//	GROUP BY od.id, n.id, fqns.fqn
func (q *Queries) GetObligation(ctx context.Context, arg GetObligationParams) (GetObligationRow, error) {
	row := q.db.QueryRowContext(ctx, getObligation, arg.ID, arg.NamespaceFqn, arg.Name)
	var i GetObligationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Namespace,
		&i.Metadata,
		&i.Values,
	)
	return i, err
}

const getObligationValue = `-- name: GetObligationValue :one
WITH obligation_triggers_agg AS (
    SELECT
        ot.obligation_value_id,
        JSON_AGG(
            JSON_BUILD_OBJECT(
                'id', ot.id,
                'action', JSON_BUILD_OBJECT(
                    'id', a.id,
                    'name', a.name
                ),
                'attribute_value', JSON_BUILD_OBJECT(
                    'id', av.id,
                    'value', av.value,
                    'fqn', COALESCE(av_fqns.fqn, '')
                ),
                'context', CASE
                    WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
                        JSON_BUILD_OBJECT(
                            'pep', JSON_BUILD_OBJECT(
                                'client_id', ot.client_id
                            )
                        )
                    )
                    ELSE '[]'
                END
            )
        ) as triggers
    FROM obligation_triggers ot
    JOIN actions a ON ot.action_id = a.id
    JOIN attribute_values av ON ot.attribute_value_id = av.id
    LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
    GROUP BY ot.obligation_value_id
)
SELECT
    ov.id,
    ov.value,
    od.id as obligation_id,
    od.name,
    JSON_BUILD_OBJECT(
        'id', n.id,
        'name', n.name,
        'fqn', fqns.fqn
    ) as namespace,
    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(ov.metadata, '$.labels'), 'created_at', ov.created_at,'updated_at', ov.updated_at)) as metadata,
    COALESCE(ota.triggers, '[]') as triggers
FROM obligation_values_standard ov
JOIN obligation_definitions od ON ov.obligation_definition_id = od.id
JOIN attribute_namespaces n ON od.namespace_id = n.id
LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
LEFT JOIN obligation_triggers_agg ota on ov.id = ota.obligation_value_id
WHERE
    -- lookup by value id OR by namespace fqn + obligation name + value name
    (
        -- lookup by value id
        ($1 IS NOT NULL AND ov.id = $1)
        OR
        -- lookup by namespace fqn + obligation name + value name
        ($2 IS NOT NULL AND $3 IS NOT NULL AND $4 IS NOT NULL
         AND fqns.fqn = $2 AND od.name = $3 AND ov.value = $4)
    )
`

type GetObligationValueParams struct {
	ID           interface{} `json:"id"`
	NamespaceFqn interface{} `json:"namespace_fqn"`
	Name         interface{} `json:"name"`
	Value        interface{} `json:"value"`
}

type GetObligationValueRow struct {
	ID           string          `json:"id"`
	Value        string          `json:"value"`
	ObligationID string          `json:"obligation_id"`
	Name         string          `json:"name"`
	Namespace    json.RawMessage `json:"namespace"`
	Metadata     json.RawMessage `json:"metadata"`
	Triggers     json.RawMessage `json:"triggers"`
}

// GetObligationValue
//
//	WITH obligation_triggers_agg AS (
//	    SELECT
//	        ot.obligation_value_id,
//	        JSON_AGG(
//	            JSON_BUILD_OBJECT(
//	                'id', ot.id,
//	                'action', JSON_BUILD_OBJECT(
//	                    'id', a.id,
//	                    'name', a.name
//	                ),
//	                'attribute_value', JSON_BUILD_OBJECT(
//	                    'id', av.id,
//	                    'value', av.value,
//	                    'fqn', COALESCE(av_fqns.fqn, '')
//	                ),
//	                'context', CASE
//	                    WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
//	                        JSON_BUILD_OBJECT(
//	                            'pep', JSON_BUILD_OBJECT(
//	                                'client_id', ot.client_id
//	                            )
//	                        )
//	                    )
//	                    ELSE '[]'
//	                END
//	            )
//	        ) as triggers
//	    FROM obligation_triggers ot
//	    JOIN actions a ON ot.action_id = a.id
//	    JOIN attribute_values av ON ot.attribute_value_id = av.id
//	    LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
//	    GROUP BY ot.obligation_value_id
//	)
//	SELECT
//	    ov.id,
//	    ov.value,
//	    od.id as obligation_id,
//	    od.name,
//	    JSON_BUILD_OBJECT(
//	        'id', n.id,
//	        'name', n.name,
//	        'fqn', fqns.fqn
//	    ) as namespace,
//	    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(ov.metadata, '$.labels'), 'created_at', ov.created_at,'updated_at', ov.updated_at)) as metadata,
//	    COALESCE(ota.triggers, '[]') as triggers
//	FROM obligation_values_standard ov
//	JOIN obligation_definitions od ON ov.obligation_definition_id = od.id
//	JOIN attribute_namespaces n ON od.namespace_id = n.id
//	LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
//	LEFT JOIN obligation_triggers_agg ota on ov.id = ota.obligation_value_id
//	WHERE
//	    -- lookup by value id OR by namespace fqn + obligation name + value name
//	    (
//	        -- lookup by value id
//	        ($1 IS NOT NULL AND ov.id = $1)
//	        OR
//	        -- lookup by namespace fqn + obligation name + value name
//	        ($2 IS NOT NULL AND $3 IS NOT NULL AND $4 IS NOT NULL
//	         AND fqns.fqn = $2 AND od.name = $3 AND ov.value = $4)
//	    )
func (q *Queries) GetObligationValue(ctx context.Context, arg GetObligationValueParams) (GetObligationValueRow, error) {
	row := q.db.QueryRowContext(ctx, getObligationValue,
		arg.ID,
		arg.NamespaceFqn,
		arg.Name,
		arg.Value,
	)
	var i GetObligationValueRow
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.ObligationID,
		&i.Name,
		&i.Namespace,
		&i.Metadata,
		&i.Triggers,
	)
	return i, err
}

const getObligationValuesByFQNs = `-- name: GetObligationValuesByFQNs :many
WITH obligation_triggers_agg AS (
    SELECT
        ot.obligation_value_id,
        JSON_AGG(
            JSON_BUILD_OBJECT(
                'id', ot.id,
                'action', JSON_BUILD_OBJECT(
                    'id', a.id,
                    'name', a.name
                ),
                'attribute_value', JSON_BUILD_OBJECT(
                    'id', av.id,
                    'value', av.value,
                    'fqn', COALESCE(av_fqns.fqn, '')
                ),
                'context', CASE
                    WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
                        JSON_BUILD_OBJECT(
                            'pep', JSON_BUILD_OBJECT(
                                'client_id', ot.client_id
                            )
                        )
                    )
                    ELSE '[]'
                END
            )
        ) as triggers
    FROM obligation_triggers ot
    JOIN actions a ON ot.action_id = a.id
    JOIN attribute_values av ON ot.attribute_value_id = av.id
    LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
    GROUP BY ot.obligation_value_id
)
SELECT
    ov.id,
    ov.value,
    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(ov.metadata, '$.labels'), 'created_at', ov.created_at,'updated_at', ov.updated_at)) as metadata,
    od.id as obligation_id,
    od.name as name,
    JSON_BUILD_OBJECT(
        'id', n.id,
        'name', n.name,
        'fqn', fqns.fqn
    ) as namespace,
    COALESCE(ota.triggers, '[]') as triggers
FROM
    obligation_values_standard ov
JOIN
    obligation_definitions od ON ov.obligation_definition_id = od.id
JOIN
    attribute_namespaces n ON od.namespace_id = n.id
JOIN
    attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
JOIN
    (SELECT ns.value as ns_fqn, nm.value as obl_name, v.value as value
     FROM json_each($1) AS ns(key, value)
     JOIN json_each($2) AS nm(key, value) ON ns.key = nm.key
     JOIN json_each($3) AS v(key, value) ON ns.key = v.key) as fqn_pairs
ON
    fqns.fqn = fqn_pairs.ns_fqn AND od.name = fqn_pairs.obl_name AND ov.value = fqn_pairs.value
LEFT JOIN
    obligation_triggers_agg ota on ov.id = ota.obligation_value_id
`

type GetObligationValuesByFQNsParams struct {
	NamespaceFqns json.RawMessage `json:"namespace_fqns"`
	Names         json.RawMessage `json:"names"`
	Values        json.RawMessage `json:"values"`
}

type GetObligationValuesByFQNsRow struct {
	ID           string          `json:"id"`
	Value        string          `json:"value"`
	Metadata     json.RawMessage `json:"metadata"`
	ObligationID string          `json:"obligation_id"`
	Name         string          `json:"name"`
	Namespace    json.RawMessage `json:"namespace"`
	Triggers     json.RawMessage `json:"triggers"`
}

// GetObligationValuesByFQNs
//
//	WITH obligation_triggers_agg AS (
//	    SELECT
//	        ot.obligation_value_id,
//	        JSON_AGG(
//	            JSON_BUILD_OBJECT(
//	                'id', ot.id,
//	                'action', JSON_BUILD_OBJECT(
//	                    'id', a.id,
//	                    'name', a.name
//	                ),
//	                'attribute_value', JSON_BUILD_OBJECT(
//	                    'id', av.id,
//	                    'value', av.value,
//	                    'fqn', COALESCE(av_fqns.fqn, '')
//	                ),
//	                'context', CASE
//	                    WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
//	                        JSON_BUILD_OBJECT(
//	                            'pep', JSON_BUILD_OBJECT(
//	                                'client_id', ot.client_id
//	                            )
//	                        )
//	                    )
//	                    ELSE '[]'
//	                END
//	            )
//	        ) as triggers
//	    FROM obligation_triggers ot
//	    JOIN actions a ON ot.action_id = a.id
//	    JOIN attribute_values av ON ot.attribute_value_id = av.id
//	    LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
//	    GROUP BY ot.obligation_value_id
//	)
//	SELECT
//	    ov.id,
//	    ov.value,
//	    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(ov.metadata, '$.labels'), 'created_at', ov.created_at,'updated_at', ov.updated_at)) as metadata,
//	    od.id as obligation_id,
//	    od.name as name,
//	    JSON_BUILD_OBJECT(
//	        'id', n.id,
//	        'name', n.name,
//	        'fqn', fqns.fqn
//	    ) as namespace,
//	    COALESCE(ota.triggers, '[]') as triggers
//	FROM
//	    obligation_values_standard ov
//	JOIN
//	    obligation_definitions od ON ov.obligation_definition_id = od.id
//	JOIN
//	    attribute_namespaces n ON od.namespace_id = n.id
//	JOIN
//	    attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
//	JOIN
//	    (SELECT ns.value as ns_fqn, nm.value as obl_name, v.value as value
//	     FROM json_each($1) AS ns(key, value)
//	     JOIN json_each($2) AS nm(key, value) ON ns.key = nm.key
//	     JOIN json_each($3) AS v(key, value) ON ns.key = v.key) as fqn_pairs
//	ON
//	    fqns.fqn = fqn_pairs.ns_fqn AND od.name = fqn_pairs.obl_name AND ov.value = fqn_pairs.value
//	LEFT JOIN
//	    obligation_triggers_agg ota on ov.id = ota.obligation_value_id
func (q *Queries) GetObligationValuesByFQNs(ctx context.Context, arg GetObligationValuesByFQNsParams) ([]GetObligationValuesByFQNsRow, error) {
	rows, err := q.db.QueryContext(ctx, getObligationValuesByFQNs, arg.NamespaceFqns, arg.Names, arg.Values)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetObligationValuesByFQNsRow
	for rows.Next() {
		var i GetObligationValuesByFQNsRow
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Metadata,
			&i.ObligationID,
			&i.Name,
			&i.Namespace,
			&i.Triggers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObligationsByFQNs = `-- name: GetObligationsByFQNs :many
WITH obligation_triggers_agg AS (
    SELECT
        ot.obligation_value_id,
        JSON_AGG(
            JSON_BUILD_OBJECT(
                'id', ot.id,
                'action', JSON_BUILD_OBJECT(
                    'id', a.id,
                    'name', a.name
                ),
                'attribute_value', JSON_BUILD_OBJECT(
                    'id', av.id,
                    'value', av.value,
                    'fqn', COALESCE(av_fqns.fqn, '')
                ),
                'context', CASE
                    WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
                        JSON_BUILD_OBJECT(
                            'pep', JSON_BUILD_OBJECT(
                                'client_id', ot.client_id
                            )
                        )
                    )
                    ELSE '[]'
                END
            )
        ) as triggers
    FROM obligation_triggers ot
    JOIN actions a ON ot.action_id = a.id
    JOIN attribute_values av ON ot.attribute_value_id = av.id
    LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
    GROUP BY ot.obligation_value_id
)
SELECT
    od.id,
    od.name,
    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(od.metadata, '$.labels'), 'created_at', od.created_at,'updated_at', od.updated_at)) as metadata,
    JSON_BUILD_OBJECT(
        'id', n.id,
        'name', n.name,
        'fqn', fqns.fqn
    ) as namespace,
    COALESCE(
        JSON_AGG(
            CASE
                WHEN ov.id IS NOT NULL THEN JSON_BUILD_OBJECT(
                    'id', ov.id,
                    'value', ov.value,
                    'triggers', COALESCE(ota.triggers, '[]')
                )
            END
        ),
        '[]'
    ) as "values"
FROM
    obligation_definitions od
JOIN
    attribute_namespaces n on od.namespace_id = n.id
JOIN
    attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
JOIN
    (SELECT ns.value as ns_fqn, nm.value as obl_name
     FROM json_each($1) AS ns(key, value)
     JOIN json_each($2) AS nm(key, value) ON ns.key = nm.key) as fqn_pairs
ON
    fqns.fqn = fqn_pairs.ns_fqn AND od.name = fqn_pairs.obl_name
LEFT JOIN
    obligation_values_standard ov on od.id = ov.obligation_definition_id
LEFT JOIN
    obligation_triggers_agg ota on ov.id = ota.obligation_value_id
GROUP BY
    od.id, n.id, fqns.fqn
`

type GetObligationsByFQNsParams struct {
	NamespaceFqns json.RawMessage `json:"namespace_fqns"`
	Names         json.RawMessage `json:"names"`
}

type GetObligationsByFQNsRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Metadata  json.RawMessage `json:"metadata"`
	Namespace json.RawMessage `json:"namespace"`
	Values    interface{}     `json:"values"`
}

// GetObligationsByFQNs
//
//	WITH obligation_triggers_agg AS (
//	    SELECT
//	        ot.obligation_value_id,
//	        JSON_AGG(
//	            JSON_BUILD_OBJECT(
//	                'id', ot.id,
//	                'action', JSON_BUILD_OBJECT(
//	                    'id', a.id,
//	                    'name', a.name
//	                ),
//	                'attribute_value', JSON_BUILD_OBJECT(
//	                    'id', av.id,
//	                    'value', av.value,
//	                    'fqn', COALESCE(av_fqns.fqn, '')
//	                ),
//	                'context', CASE
//	                    WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
//	                        JSON_BUILD_OBJECT(
//	                            'pep', JSON_BUILD_OBJECT(
//	                                'client_id', ot.client_id
//	                            )
//	                        )
//	                    )
//	                    ELSE '[]'
//	                END
//	            )
//	        ) as triggers
//	    FROM obligation_triggers ot
//	    JOIN actions a ON ot.action_id = a.id
//	    JOIN attribute_values av ON ot.attribute_value_id = av.id
//	    LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
//	    GROUP BY ot.obligation_value_id
//	)
//	SELECT
//	    od.id,
//	    od.name,
//	    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(od.metadata, '$.labels'), 'created_at', od.created_at,'updated_at', od.updated_at)) as metadata,
//	    JSON_BUILD_OBJECT(
//	        'id', n.id,
//	        'name', n.name,
//	        'fqn', fqns.fqn
//	    ) as namespace,
//	    COALESCE(
//	        JSON_AGG(
//	            CASE
//	                WHEN ov.id IS NOT NULL THEN JSON_BUILD_OBJECT(
//	                    'id', ov.id,
//	                    'value', ov.value,
//	                    'triggers', COALESCE(ota.triggers, '[]')
//	                )
//	            END
//	        ),
//	        '[]'
//	    ) as "values"
//	FROM
//	    obligation_definitions od
//	JOIN
//	    attribute_namespaces n on od.namespace_id = n.id
//	JOIN
//	    attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
//	JOIN
//	    (SELECT ns.value as ns_fqn, nm.value as obl_name
//	     FROM json_each($1) AS ns(key, value)
//	     JOIN json_each($2) AS nm(key, value) ON ns.key = nm.key) as fqn_pairs
//	ON
//	    fqns.fqn = fqn_pairs.ns_fqn AND od.name = fqn_pairs.obl_name
//	LEFT JOIN
//	    obligation_values_standard ov on od.id = ov.obligation_definition_id
//	LEFT JOIN
//	    obligation_triggers_agg ota on ov.id = ota.obligation_value_id
//	GROUP BY
//	    od.id, n.id, fqns.fqn
func (q *Queries) GetObligationsByFQNs(ctx context.Context, arg GetObligationsByFQNsParams) ([]GetObligationsByFQNsRow, error) {
	rows, err := q.db.QueryContext(ctx, getObligationsByFQNs, arg.NamespaceFqns, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetObligationsByFQNsRow
	for rows.Next() {
		var i GetObligationsByFQNsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metadata,
			&i.Namespace,
			&i.Values,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObligationTriggers = `-- name: ListObligationTriggers :many
SELECT
    JSON_STRIP_NULLS(
        JSON_BUILD_OBJECT(
            'id', ot.id,
            'obligation_value', JSON_BUILD_OBJECT(
                'id', ov.id,
                'value', ov.value,
                'obligation', JSON_BUILD_OBJECT(
                    'id', od.id,
                    'name', od.name,
                    'namespace', JSON_BUILD_OBJECT(
                        'id', n.id,
                        'name', n.name,
                        'fqn', COALESCE(ns_fqns.fqn, '')
                    )
                )
            ),
            'action', JSON_BUILD_OBJECT(
                'id', a.id,
                'name', a.name
            ),
            'attribute_value', JSON_BUILD_OBJECT(
                'id', av.id,
                'value', av.value,
                'fqn', COALESCE(av_fqns.fqn, '')
            ),
            'context', CASE
                WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
                    JSON_BUILD_OBJECT(
                        'pep', JSON_BUILD_OBJECT(
                            'client_id', ot.client_id
                        )
                    )
                )
                ELSE '[]'
            END
        )
    ) as "trigger",
    JSON_STRIP_NULLS(
        JSON_BUILD_OBJECT(
            'labels', json_extract(ot.metadata, '$.labels'),
            'created_at', ot.created_at,
            'updated_at', ot.updated_at
        )
    ) as metadata,
    COUNT(*) OVER() as total
FROM obligation_triggers ot
JOIN obligation_values_standard ov ON ot.obligation_value_id = ov.id
JOIN obligation_definitions od ON ov.obligation_definition_id = od.id
JOIN attribute_namespaces n ON od.namespace_id = n.id
LEFT JOIN attribute_fqns ns_fqns ON ns_fqns.namespace_id = n.id AND ns_fqns.attribute_id IS NULL AND ns_fqns.value_id IS NULL
JOIN actions a ON ot.action_id = a.id
JOIN attribute_values av ON ot.attribute_value_id = av.id
LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
WHERE
    ($1 IS NULL OR od.namespace_id = $1) AND
    ($2 IS NULL OR ns_fqns.fqn = $2)
ORDER BY ot.created_at DESC
LIMIT $4
OFFSET $3
`

type ListObligationTriggersParams struct {
	NamespaceID  interface{} `json:"namespace_id"`
	NamespaceFqn interface{} `json:"namespace_fqn"`
	Offset       int32       `json:"offset_"`
	Limit        int32       `json:"limit_"`
}

type ListObligationTriggersRow struct {
	Trigger  json.RawMessage `json:"trigger"`
	Metadata json.RawMessage `json:"metadata"`
	Total    int64           `json:"total"`
}

// ListObligationTriggers
//
//	SELECT
//	    JSON_STRIP_NULLS(
//	        JSON_BUILD_OBJECT(
//	            'id', ot.id,
//	            'obligation_value', JSON_BUILD_OBJECT(
//	                'id', ov.id,
//	                'value', ov.value,
//	                'obligation', JSON_BUILD_OBJECT(
//	                    'id', od.id,
//	                    'name', od.name,
//	                    'namespace', JSON_BUILD_OBJECT(
//	                        'id', n.id,
//	                        'name', n.name,
//	                        'fqn', COALESCE(ns_fqns.fqn, '')
//	                    )
//	                )
//	            ),
//	            'action', JSON_BUILD_OBJECT(
//	                'id', a.id,
//	                'name', a.name
//	            ),
//	            'attribute_value', JSON_BUILD_OBJECT(
//	                'id', av.id,
//	                'value', av.value,
//	                'fqn', COALESCE(av_fqns.fqn, '')
//	            ),
//	            'context', CASE
//	                WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
//	                    JSON_BUILD_OBJECT(
//	                        'pep', JSON_BUILD_OBJECT(
//	                            'client_id', ot.client_id
//	                        )
//	                    )
//	                )
//	                ELSE '[]'
//	            END
//	        )
//	    ) as "trigger",
//	    JSON_STRIP_NULLS(
//	        JSON_BUILD_OBJECT(
//	            'labels', json_extract(ot.metadata, '$.labels'),
//	            'created_at', ot.created_at,
//	            'updated_at', ot.updated_at
//	        )
//	    ) as metadata,
//	    COUNT(*) OVER() as total
//	FROM obligation_triggers ot
//	JOIN obligation_values_standard ov ON ot.obligation_value_id = ov.id
//	JOIN obligation_definitions od ON ov.obligation_definition_id = od.id
//	JOIN attribute_namespaces n ON od.namespace_id = n.id
//	LEFT JOIN attribute_fqns ns_fqns ON ns_fqns.namespace_id = n.id AND ns_fqns.attribute_id IS NULL AND ns_fqns.value_id IS NULL
//	JOIN actions a ON ot.action_id = a.id
//	JOIN attribute_values av ON ot.attribute_value_id = av.id
//	LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
//	WHERE
//	    ($1 IS NULL OR od.namespace_id = $1) AND
//	    ($2 IS NULL OR ns_fqns.fqn = $2)
//	ORDER BY ot.created_at DESC
//	LIMIT $4
//	OFFSET $3
func (q *Queries) ListObligationTriggers(ctx context.Context, arg ListObligationTriggersParams) ([]ListObligationTriggersRow, error) {
	rows, err := q.db.QueryContext(ctx, listObligationTriggers,
		arg.NamespaceID,
		arg.NamespaceFqn,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObligationTriggersRow
	for rows.Next() {
		var i ListObligationTriggersRow
		if err := rows.Scan(&i.Trigger, &i.Metadata, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObligations = `-- name: ListObligations :many
WITH counted AS (
    SELECT COUNT(od.id) AS total
    FROM obligation_definitions od
    LEFT JOIN attribute_namespaces n ON od.namespace_id = n.id
    LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
    WHERE
        ($1 IS NULL OR od.namespace_id = $1) AND
        ($2 IS NULL OR fqns.fqn = $2)
),
obligation_triggers_agg AS (
    SELECT
        ot.obligation_value_id,
        JSON_AGG(
            JSON_BUILD_OBJECT(
                'id', ot.id,
                'action', JSON_BUILD_OBJECT(
                    'id', a.id,
                    'name', a.name
                ),
                'attribute_value', JSON_BUILD_OBJECT(
                    'id', av.id,
                    'value', av.value,
                    'fqn', COALESCE(av_fqns.fqn, '')
                ),
                'context', CASE
                    WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
                        JSON_BUILD_OBJECT(
                            'pep', JSON_BUILD_OBJECT(
                                'client_id', ot.client_id
                            )
                        )
                    )
                    ELSE '[]'
                END
            )
        ) as triggers
    FROM obligation_triggers ot
    JOIN actions a ON ot.action_id = a.id
    JOIN attribute_values av ON ot.attribute_value_id = av.id
    LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
    GROUP BY ot.obligation_value_id
)
SELECT
    od.id,
    od.name,
    JSON_BUILD_OBJECT(
        'id', n.id,
        'name', n.name,
        'fqn', fqns.fqn
    ) as namespace,
    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(od.metadata, '$.labels'), 'created_at', od.created_at,'updated_at', od.updated_at)) as metadata,
    JSON_AGG(
        CASE
            WHEN ov.id IS NOT NULL THEN JSON_BUILD_OBJECT(
                'id', ov.id,
                'value', ov.value,
                'triggers', COALESCE(ota.triggers, '[]')
            )
        END
    ) as "values",
    counted.total
FROM obligation_definitions od
JOIN attribute_namespaces n on od.namespace_id = n.id
LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
CROSS JOIN counted
LEFT JOIN obligation_values_standard ov on od.id = ov.obligation_definition_id
LEFT JOIN obligation_triggers_agg ota on ov.id = ota.obligation_value_id
WHERE
    ($1 IS NULL OR od.namespace_id = $1) AND
    ($2 IS NULL OR fqns.fqn = $2)
GROUP BY od.id, n.id, fqns.fqn, counted.total
ORDER BY od.created_at DESC
LIMIT $4
OFFSET $3
`

type ListObligationsParams struct {
	NamespaceID  interface{} `json:"namespace_id"`
	NamespaceFqn interface{} `json:"namespace_fqn"`
	Offset       int32       `json:"offset_"`
	Limit        int32       `json:"limit_"`
}

type ListObligationsRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Namespace json.RawMessage `json:"namespace"`
	Metadata  json.RawMessage `json:"metadata"`
	Values    json.RawMessage `json:"values"`
	Total     int64           `json:"total"`
}

// ListObligations
//
//	WITH counted AS (
//	    SELECT COUNT(od.id) AS total
//	    FROM obligation_definitions od
//	    LEFT JOIN attribute_namespaces n ON od.namespace_id = n.id
//	    LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
//	    WHERE
//	        ($1 IS NULL OR od.namespace_id = $1) AND
//	        ($2 IS NULL OR fqns.fqn = $2)
//	),
//	obligation_triggers_agg AS (
//	    SELECT
//	        ot.obligation_value_id,
//	        JSON_AGG(
//	            JSON_BUILD_OBJECT(
//	                'id', ot.id,
//	                'action', JSON_BUILD_OBJECT(
//	                    'id', a.id,
//	                    'name', a.name
//	                ),
//	                'attribute_value', JSON_BUILD_OBJECT(
//	                    'id', av.id,
//	                    'value', av.value,
//	                    'fqn', COALESCE(av_fqns.fqn, '')
//	                ),
//	                'context', CASE
//	                    WHEN ot.client_id IS NOT NULL THEN JSON_BUILD_ARRAY(
//	                        JSON_BUILD_OBJECT(
//	                            'pep', JSON_BUILD_OBJECT(
//	                                'client_id', ot.client_id
//	                            )
//	                        )
//	                    )
//	                    ELSE '[]'
//	                END
//	            )
//	        ) as triggers
//	    FROM obligation_triggers ot
//	    JOIN actions a ON ot.action_id = a.id
//	    JOIN attribute_values av ON ot.attribute_value_id = av.id
//	    LEFT JOIN attribute_fqns av_fqns ON av_fqns.value_id = av.id
//	    GROUP BY ot.obligation_value_id
//	)
//	SELECT
//	    od.id,
//	    od.name,
//	    JSON_BUILD_OBJECT(
//	        'id', n.id,
//	        'name', n.name,
//	        'fqn', fqns.fqn
//	    ) as namespace,
//	    JSON_STRIP_NULLS(JSON_BUILD_OBJECT('labels', json_extract(od.metadata, '$.labels'), 'created_at', od.created_at,'updated_at', od.updated_at)) as metadata,
//	    JSON_AGG(
//	        CASE
//	            WHEN ov.id IS NOT NULL THEN JSON_BUILD_OBJECT(
//	                'id', ov.id,
//	                'value', ov.value,
//	                'triggers', COALESCE(ota.triggers, '[]')
//	            )
//	        END
//	    ) as "values",
//	    counted.total
//	FROM obligation_definitions od
//	JOIN attribute_namespaces n on od.namespace_id = n.id
//	LEFT JOIN attribute_fqns fqns ON fqns.namespace_id = n.id AND fqns.attribute_id IS NULL AND fqns.value_id IS NULL
//	CROSS JOIN counted
//	LEFT JOIN obligation_values_standard ov on od.id = ov.obligation_definition_id
//	LEFT JOIN obligation_triggers_agg ota on ov.id = ota.obligation_value_id
//	WHERE
//	    ($1 IS NULL OR od.namespace_id = $1) AND
//	    ($2 IS NULL OR fqns.fqn = $2)
//	GROUP BY od.id, n.id, fqns.fqn, counted.total
//	ORDER BY od.created_at DESC
//	LIMIT $4
//	OFFSET $3
func (q *Queries) ListObligations(ctx context.Context, arg ListObligationsParams) ([]ListObligationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listObligations,
		arg.NamespaceID,
		arg.NamespaceFqn,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObligationsRow
	for rows.Next() {
		var i ListObligationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Namespace,
			&i.Metadata,
			&i.Values,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateObligation = `-- name: UpdateObligation :execrows
UPDATE obligation_definitions
SET
    name = COALESCE($1, name),
    metadata = COALESCE($2, metadata),
    updated_at = STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now', '+0.001 seconds')
WHERE id = $3
`

type UpdateObligationParams struct {
	Name     sql.NullString `json:"name"`
	Metadata sql.NullString `json:"metadata"`
	ID       string         `json:"id"`
}

// UpdateObligation
//
//	UPDATE obligation_definitions
//	SET
//	    name = COALESCE($1, name),
//	    metadata = COALESCE($2, metadata)
//	WHERE id = $3
func (q *Queries) UpdateObligation(ctx context.Context, arg UpdateObligationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateObligation, arg.Name, arg.Metadata, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateObligationValue = `-- name: UpdateObligationValue :execrows
UPDATE obligation_values_standard
SET
    value = COALESCE($1, value),
    metadata = COALESCE($2, metadata),
    updated_at = STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now', '+0.001 seconds')
WHERE id = $3
`

type UpdateObligationValueParams struct {
	Value    sql.NullString `json:"value"`
	Metadata sql.NullString `json:"metadata"`
	ID       string         `json:"id"`
}

// UpdateObligationValue
//
//	UPDATE obligation_values_standard
//	SET
//	    value = COALESCE($1, value),
//	    metadata = COALESCE($2, metadata)
//	WHERE id = $3
func (q *Queries) UpdateObligationValue(ctx context.Context, arg UpdateObligationValueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateObligationValue, arg.Value, arg.Metadata, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
